In [2]:
!pip install gym

Defaulting to user installation because normal site-packages is not writeable
  Using cached gym-0.26.2-py3-none-any.whl


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mlagents-envs 0.30.0 requires numpy==1.21.2, but you have numpy 1.26.4 which is incompatible.


In [3]:
import gym
import numpy as np 
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
tensor = tf.constant([[1,2],[3,4]])

In [5]:
print("Tensor:")
print(tensor)

Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
variable = tf.Variable(tf.zeros([2,2]))

In [7]:
print("\nvariable:")
print(variable)


variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>


In [8]:
variable.assign_add(tf.ones([2,2]))

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [9]:
print("\nUpdated Variable:")
print(variable)


Updated Variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>


In [18]:
import gym
import random
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Flatten
# from tensorflow.keras.optimizers import Adam
# 
# 
# from rl.policy import BoltzmannQPolicy
# from rl.memory import SequentialMemory


env = gym.make("CartPole-v1", render_mode = "human")

states = env.observation_space.shape[0]
actions = env.action_space.n

print(states)
print(actions)



episodes = 10
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        action = random.choice([0, 1])
        obs, reward, terminated, truncated , info = env.step(action)
        print(obs, reward, terminated, truncated, info)
        score += reward
        env.render()

    print(f"Episode {episode}, Score: {score}")

env.close()


4
2
[ 0.04107186  0.16505347 -0.01752185 -0.31520292] 1.0 False False {}
[ 0.04437293 -0.02981456 -0.02382591 -0.02809691] 1.0 False False {}
[ 0.04377664  0.16564082 -0.02438785 -0.32820094] 1.0 False False {}
[ 0.04708946 -0.0291256  -0.03095187 -0.04330749] 1.0 False False {}
[ 0.04650695 -0.22379035 -0.03181802  0.23945138] 1.0 False False {}
[ 0.04203114 -0.41844365 -0.02702899  0.52193063] 1.0 False False {}
[ 0.03366227 -0.22295189 -0.01659038  0.22085454] 1.0 False False {}
[ 0.02920323 -0.41783282 -0.01217329  0.50825834] 1.0 False False {}
[ 0.02084657 -0.2225415  -0.00200812  0.21176422] 1.0 False False {}
[ 0.01639574 -0.02739089  0.00222716 -0.08155149] 1.0 False False {}
[ 0.01584793 -0.22254469  0.00059613  0.21183327] 1.0 False False {}
[ 0.01139703 -0.41767517  0.0048328   0.5047042 ] 1.0 False False {}
[ 0.00304353 -0.22262165  0.01492688  0.21354818] 1.0 False False {}
[-0.00140891 -0.4179538   0.01919785  0.5109021 ] 1.0 False False {}
[-0.00976798 -0.22310747  0.02

[-1.8882337  -0.03347425 10.578842    8.221605  ] 0.0 True False {}
[-1.8889033   0.08857026 10.743275    8.026867  ] 0.0 True False {}
[-1.8871318   0.21095918 10.903811    7.7880034 ] 0.0 True False {}
[-1.8829126   0.33672285 11.059572    7.5125265 ] 0.0 True False {}
[-1.8761781  0.4682283 11.209823   7.206513 ] 0.0 True False {}
[-1.8668135   0.24235718 11.353952    6.9912696 ] 0.0 True False {}
[-1.8619665   0.38817677 11.493778    6.6392274 ] 0.0 True False {}
[-1.8542029   0.54281086 11.626562    6.270128  ] 0.0 True False {}
[-1.8433467  0.3335339 11.7519655  6.2179313] 0.0 True False {}
[-1.836676    0.50186485 11.876324    5.8308115 ] 0.0 True False {}
[-1.8266387  0.2986932 11.99294    5.8786926] 0.0 True False {}
[-1.8206649   0.47819382 12.110514    5.49301   ] 0.0 True False {}
[-1.811101    0.66339904 12.220374    5.1141424 ] 0.0 True False {}
[-1.797833   0.4658614 12.322657   5.293184 ] 0.0 True False {}
[-1.7885158  0.6569317 12.42852    4.9441032] 0.0 True False {}


[ 2.4252903  3.1541457 28.709955  10.631824 ] 0.0 True False {}
[ 2.4883733  2.910181  28.922592  10.175993 ] 0.0 True False {}
[ 2.546577   2.6539917 29.126112   9.692149 ] 0.0 True False {}
[ 2.5996568  2.76831   29.319956   9.583871 ] 0.0 True False {}
[ 2.655023   2.5039158 29.511633   9.130654 ] 0.0 True False {}
[ 2.7051013  2.2444544 29.694246   8.725451 ] 0.0 True False {}
[ 2.7499905  1.9918351 29.868755   8.377833 ] 0.0 True False {}
[ 2.789827  2.110184 30.036312  8.079722] 0.0 True False {}
[ 2.8320308  1.8720065 30.197906   7.858966 ] 0.0 True False {}
[ 2.8694708  1.6399417 30.355085   7.70334  ] 0.0 True False {}
[ 2.9022698  1.7826893 30.509151   7.342226 ] 0.0 True False {}
[ 2.9379234  1.9363791 30.655996   6.9686193] 0.0 True False {}
[ 2.9766512  2.1003327 30.795368   6.58782  ] 0.0 True False {}
[ 3.0186577  2.273338  30.927126   6.2057385] 0.0 True False {}
[ 3.0641246  2.069803  31.05124    6.337236 ] 0.0 True False {}
[ 3.1055205  1.8673698 31.177984   6.51606  

KeyboardInterrupt: 